### ISSUE TITLE
Relies on the FreeImage binary

### ISSUE THREAD

**Issue by gabe2010** [liamlangli/vat#3]
Not really an issue per se but I was struggling to get this to work, after googling about a bit I found I was missing FreeImage binary on my system which is needed for Imageio to write the EXR file. Was able to download it from here: https://imageio.readthedocs.io/en/v2.5.0/format_exr-fi.html
Thanks

**Comment by liamlangli** [comment]
Thanks for the solution on this issue, and one more question, are you using Window platform?
The scripts of this tool is made on macOS platform, it is easy to install FreeImage dependencies via Homebrew.

**Comment by gabe2010** [comment]
Yes on windows

**Comment by liamlangli** [comment]
I'll close this issue and add this solution to readme file to help windows users deal with this problem.
